version: 0.2

phases:

  install:
    commands:
          - npm install

  build:
    commands:
          - npm run build


  # post_build:
  #   commands:

artifacts:
  files:
    - 'dist/**/*'
    - 'codepipeline-eu-west-1-700310422187'
