version: 0.2

phases:

  install:
    commands:
          - npm install

  build:
    commands:
          - npm run build

  post_build:
    commands:
          - cd ./build && npm install --production

artifacts:
  files:
    - './**/*'
  name: build-demo2-artifacts
  base-directory: 'build'
